version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: |
      /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sugomori
    depends_on:
      - db
  db:
    image: postgres:9.5.18
    environment:
      POSTGRES_PASSWORD: password

volumes:
  dbdata:
